import {
    CREATE_SESSION_START,
    CREATE_SESSION_SUCCESS,
    UNAUTHORIZED_SESSION,
} from '../../domain/session/actions/SessionActions';

import {
    FLASH_MESSAGE_SHOW,
    FLASH_MESSAGE_SHOW_WITH_REMOVAL_TIMER,
    FLASH_MESSAGE_START_REMOVAL_TIMER,
    FLASH_MESSAGE_STOP_REMOVAL_TIMER,
    FLASH_MESSAGE_REMOVE
} from '../../domain/flashMessage/actions/FlashMessageActions';

/**
 * @property ALLOWED_ACTION_TYPES
 * @type {Array}
 * @final
 */
export const ALLOWED_ACTION_TYPES = [
    CREATE_SESSION_START,
    CREATE_SESSION_SUCCESS,
    FLASH_MESSAGE_SHOW,
    FLASH_MESSAGE_SHOW_WITH_REMOVAL_TIMER,
    FLASH_MESSAGE_START_REMOVAL_TIMER,
    FLASH_MESSAGE_STOP_REMOVAL_TIMER,
    FLASH_MESSAGE_REMOVE,
    UNAUTHORIZED_SESSION
];
